language: node_js
sudo: false
node_js:
  - "4"
  - "5"
cache:
  directories:
  - node_modules
env:
  global:
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/react-metrics-build/logs
    - USE_CLOUD=false
matrix:
  fast_finish: true
  include:
    - node_js: stable
      env: USE_CLOUD=true
  allow_failures:
    - env: USE_CLOUD=true
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - mkdir -p $LOGS_DIR
  - ./scripts/setup.sh
script:
  - npm test
after_script:
  - ./scripts/teardown.sh
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
